CREATE TABLE Dim_Dates (
    Date_ID SERIAL PRIMARY KEY,
    Full_Date DATE NOT NULL,
    Day INT GENERATED ALWAYS AS (EXTRACT(DAY FROM Full_Date)) STORED,
    Month INT GENERATED ALWAYS AS (EXTRACT(MONTH FROM Full_Date)) STORED,
    Year INT GENERATED ALWAYS AS (EXTRACT(YEAR FROM Full_Date)) STORED,
    Quarter INT GENERATED ALWAYS AS (EXTRACT(QUARTER FROM Full_Date)) STORED
);
